### ISSUE TITLE
libkaldi-jni.so

### ISSUE THREAD

**Issue by LqNoob** [ahmetaa/kaldi-jni#1]
I didn't find the original jni file, there is only the corresponding header file. I am also studying this direction. Can you refer to your jni source code?

**Comment by ahmetaa** [comment]
Code is still very primitive and not yet ready. I will provide it when it actually does something.

**Comment by LqNoob** [comment]
Thank you for your prompt response.
  Wait for the news, thank you!

**Comment by JuneRen** [comment]
Hello, how is the file libkaldi-jni.so compiled by which file? The ../kaldi.mk file in the makefile was not found?
